In [2]:
import numpy as np

In [3]:
def qr(A):

    n = A.shape[0]

    #Comencem amb la matriu A i la identitat
    Q = np.copy(A)
    R = np.identity(n)

    #Per cada vector columna:
    for col1 in range(n):
        for col2 in range(col1):

            #Restem la projecció als anteriors
            fact = np.dot(Q[:,col1], Q[:, col2])
            Q[:, col1] -= Q[:, col2] * fact

            #Guardem el canvi contrari a la matriu R, obs. que és per sobre de la diagonal
            R[col2, col1] = fact

        #Dividim per la norma
        fact = np.linalg.norm(Q[:, col1])
        Q[:, col1] /= fact

        #Guardem aquesta norma a la matriu R
        R[col1, col1] = fact

        print(Q)
        print(R)
        print("\n")


    return Q, R

In [4]:
#Exemple
np.set_printoptions(precision = 4, suppress=True)
A = np.asarray([[1., 1., 0.], [0., 1., 1.], [1., 0., 1.]])
print(A)
print("\n")
Q, R = qr(A)

[[1. 1. 0.]
 [0. 1. 1.]
 [1. 0. 1.]]


[[0.7071 1.     0.    ]
 [0.     1.     1.    ]
 [0.7071 0.     1.    ]]
[[1.4142 0.     0.    ]
 [0.     1.     0.    ]
 [0.     0.     1.    ]]


[[ 0.7071  0.4082  0.    ]
 [ 0.      0.8165  1.    ]
 [ 0.7071 -0.4082  1.    ]]
[[1.4142 0.7071 0.    ]
 [0.     1.2247 0.    ]
 [0.     0.     1.    ]]


[[ 0.7071  0.4082 -0.5774]
 [ 0.      0.8165  0.5774]
 [ 0.7071 -0.4082  0.5774]]
[[1.4142 0.7071 0.7071]
 [0.     1.2247 0.4082]
 [0.     0.     1.1547]]




In [5]:
#Q és ortogonal
Q @ Q.T

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

In [6]:
#R és triangular superior
R

array([[1.4142, 0.7071, 0.7071],
       [0.    , 1.2247, 0.4082],
       [0.    , 0.    , 1.1547]])

In [7]:
#A = QR
Q @ R

array([[1., 1., 0.],
       [0., 1., 1.],
       [1., 0., 1.]])

In [8]:
def lu(A):

    n = A.shape[0]

    #Comencem amb A i la identitat
    U = np.copy(A)
    L = np.identity(n)

    #Per cada fila, fem reducció amb les anteriors
    for fila1 in range(n):
        for fila2 in range(fila1):

            #Restem un múltiple de l'anterior per posar un 0 per sota de la diagonal a U
            fact = U[fila1, fila2] / U[fila2, fila2]
            U[fila1] -= fact * U[fila2]

            #Ara guardem el canvi a L per preservar el producte
            L[fila1, fila2] = fact
            
        print(L)
        print(U)
        print("\n")

    return L, U

In [9]:
#Exemple
A = np.asarray([[1., 2., 3.], [3., 2., 1.], [1., 5., 1.]])
print(A)
print("\n")
L, U = lu(A)

[[1. 2. 3.]
 [3. 2. 1.]
 [1. 5. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2. 3.]
 [3. 2. 1.]
 [1. 5. 1.]]


[[1. 0. 0.]
 [3. 1. 0.]
 [0. 0. 1.]]
[[ 1.  2.  3.]
 [ 0. -4. -8.]
 [ 1.  5.  1.]]


[[ 1.    0.    0.  ]
 [ 3.    1.    0.  ]
 [ 1.   -0.75  1.  ]]
[[ 1.  2.  3.]
 [ 0. -4. -8.]
 [ 0.  0. -8.]]




In [10]:
#Triangular inferior
L

array([[ 1.  ,  0.  ,  0.  ],
       [ 3.  ,  1.  ,  0.  ],
       [ 1.  , -0.75,  1.  ]])

In [11]:
#Triangular superior
U

array([[ 1.,  2.,  3.],
       [ 0., -4., -8.],
       [ 0.,  0., -8.]])

In [12]:
#A = LU
L @ U

array([[1., 2., 3.],
       [3., 2., 1.],
       [1., 5., 1.]])